env:
  global:
    - FOO='$BAR'
    - BAR=oops
script:
  - echo '$FOO'
  - echo \$FOO
  - echo $FOO
deploy:
  provider: script
  script: 
    echo $FOO && echo \$FOO && echo \\$FOO
  on:
    all_branches: true
